server:
  port: 8888
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:12010/eureka
    fetch-registry: true
    registry-fetch-interval-seconds: 10
  #service-provider:
  # ribbon:
  #   NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 设置hystrix的超时时间为6000ms
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 6000

#feign:
#  hystrix:
#    enabled: true # 开启Feign的熔断功能

#ribbon:
#  eureka:
#    enabled: true
